services:
  mysqldb:
    image: mysql:8
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: .env
    networks:
      - portal_editais_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5

  portalback:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    depends_on:
      mysqldb:
        condition: service_healthy
      minio:
        condition: service_started
    env_file: .env
    networks:
      - portal_editais_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - portal_editais_network

networks:
  portal_editais_network:
    name: portal_editais_network

volumes:
  mysql-data:
  minio-data:
